version: "3"
name: "transcendence"

services:

# DB
  database:
    image: postgres:15-alpine
    container_name: database
    # build: ${DB_PATH}
    restart: always
    user: postgres
    env_file: ${DB_PATH}/.env
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: u8Wqc7ABxC6RxxenPCT&
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - type: bind
        source: ${PGDATA_PATH}
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

# BACKEND
  backend:
    image: backend:v1
    container_name: backend
    build:
      context: ${BACK_PATH} # maybe just replace with regular one-line build?
      dockerfile: ${BACK_PATH}/Dockerfile
    restart: always
    environment:
      - name=value
    depends_on: 
      - database
    networks:
      - backend
    env_file: ${BACK_PATH}/.env
  
# FRONTEND
  frontend:
    image: frontend:v1
    container_name: frontend
    build:
      context: ${FRONT_PATH}
      dockerfile: ${FRONT_PATH}/Dockerfile
    working_dir: /app
    command: sh -c "yarn install
                    && yarn run build
                    && yarn global add serve
                    && serve -s build -l 3000"
    environment:
      - PUBLIC_URL=${FRONT_URL}
      - REACT_APP_BACKEND_URL=${BACK_URL}
      - REACT_APP_BACKEND_SOCKET=${SOCKET_URL}
    volumes:
      - ${FRONT_PATH}:/app
    ports:
      # - "$HOST_IP:3000:3000"
      - "3000:3000"
    # restart: unless-stopped
    networks:
      - backend
    depends_on:
      - backend
    env_file: ${FRONT_PATH}/.env


networks:
  backend:
