version: "3"
name: "transcendence"

services:
  # https://www.tomray.dev/nestjs-docker-production
  # https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/
  database:
    image: postgres:alpine
    restart: always
    env_file: ${DB_PATH}/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    # https://docs.docker.com/engine/reference/builder/#healthcheck
    # https://github.com/peter-evans/docker-compose-healthcheck
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval: 1s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
    driver: local
    driver_opts:
      device: ${HOME}/data/db
      type: none
      o: bind
